-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color8 = '#242729'
local Color3 = '#ff6b75'
local Color6 = '#596570'
local Color12 = '#272a2c'
local Color13 = '#5d2626'
local Color4 = '#46F263'
local Color0 = '#ff2525'
local Color2 = '#e24a3e'
local Color7 = '#f03022'
local Color5 = '#96b7fb'
local Color9 = '#F8F8F2'
local Color11 = '#222b27'
local Color1 = '#F6E9CB'
local Color10 = '#5f2c2c'

highlight('Error', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Keyword', nil, Color2, nil)
highlight('Operator', nil, Color3, nil)
highlight('Type', nil, Color4, nil)
highlight('Number', nil, Color5, nil)
highlight('Comment', nil, Color6, 'italic')
highlight('StatusLine', nil, Color7, nil)
highlight('WildMenu', Color8, Color9, nil)
highlight('Pmenu', Color8, Color9, nil)
highlight('PmenuSel', Color9, Color10, nil)
highlight('PmenuThumb', Color8, Color9, nil)
highlight('DiffAdd', Color11, nil, nil)
highlight('DiffDelete', Color12, nil, nil)
highlight('Normal', Color8, Color9, nil)
highlight('Visual', Color13, nil, nil)
highlight('CursorLine', Color13, nil, nil)
highlight('ColorColumn', Color13, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('LineNr', nil, Color6, nil)
highlight('TabLine', Color8, nil, nil)
highlight('TabLineSel', nil, Color10, nil)
highlight('TabLineFill', Color8, nil, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('TSKeyword', 'Keyword')
link('TSField', 'Constant')
link('TelescopeNormal', 'Normal')
link('TSLabel', 'Type')
link('TSOperator', 'Operator')
link('TSString', 'String')
link('TSRepeat', 'Repeat')
link('TSNamespace', 'TSType')
link('TSProperty', 'TSField')
link('Whitespace', 'Comment')
link('Operator', 'Keyword')
link('TSNumber', 'Number')
link('TSTag', 'MyTag')
link('TSPunctBracket', 'MyTag')
link('TSFunction', 'Function')
link('TSFloat', 'Number')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('CursorLineNr', 'Identifier')
link('TSParameterReference', 'TSParameter')
link('Repeat', 'Conditional')
link('TSConstant', 'Constant')
link('TSConditional', 'Conditional')
link('TSParameter', 'Constant')
link('NonText', 'Comment')
link('TSFuncMacro', 'Macro')
link('TSTagDelimiter', 'Type')
link('Folded', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Macro', 'Function')
link('TSComment', 'Comment')
link('Conditional', 'Operator')
link('TSType', 'Type')
